"""CSV contract shared with the existing SPI database importer."""

DB_COLUMNS = [
    "uuid",
    "line",
    "product",
    "site",
    "station_id",
    "factory",
    "carrier_sn",
    "timestamp_str",
    "csv_filename",
    "dat_filename",
    "insp_st_time",
    "array_id",
    "pad_id",
    "pad_no",
    "testresult",
    "warnresult",
    "is_pass",
    "component_id",
    "width",
    "length",
    "x",
    "y",
    "stencil",
    "vol_l_ng",
    "vol_h_ng",
    "vol_l_wn",
    "vol_h_wn",
    "hei_l_ng",
    "hei_h_ng",
    "hei_l_wn",
    "hei_h_wn",
    "area_l_ng",
    "area_h_ng",
    "area_l_wn",
    "area_h_wn",
    "shift_x_ng",
    "shift_y_ng",
    "shift_wn",
    "insp_vol",
    "insp_area",
    "insp_hei",
    "insp_x",
    "insp_y",
    "insp_shape",
    "insp_shape_area",
    "img_name",
    "anomaly_score",
    "min_pad_distance",
    "ai_defect_name",
    "dat_worktime",
    "dat_board_barcode",
    "dat_lot_no",
    "dat_component_name",
    "dat_pin_num",
    "dat_package_name",
    "dat_result",
    "dat_ng_type",
    "dat_confirm_type",
    "dat_volume_pct",
    "dat_area_pct",
    "dat_height_pct",
    "dat_offsetx_pct",
    "dat_offsety_pct",
    "dat_volume_abs",
    "dat_area_abs",
    "dat_height_abs",
    "dat_offsetx_abs",
    "dat_offsety_abs",
    "dat_stencil",
    "dat_jigcode",
    "dat_barcode_badmark",
    "dat_operator_id",
]

CSV_RENAME_MAP = {
    "Insp_st_time": "insp_st_time",
    "Array_id": "array_id",
    "Pad_id": "pad_id",
    "Pad_no": "pad_no",
    "Testresult": "testresult",
    "Warnresult": "warnresult",
    "Width": "width",
    "Length": "length",
    "X": "x",
    "Y": "y",
    "Stencil": "stencil",
}
